
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm start

  api:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4080:3000"  # Next.js default port for API app
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    volumes:
      - ./back-end:/app
      - /app/node_modules
    command: sh -c "npm start"

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myappdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
