
services:
  frontend:
    build: ./front-end
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm run docker-dev

  api:
    build: ./back-end
    ports:
      - "4080:3000"  # Next.js default port for API app
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    volumes:
      - ./back-end:/app
      - /app/node_modules
    command: sh -c "npm run docker-dev"

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${mydb}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
