
services:
  frontend:
    build: ./front-end
    ports:
      - "80:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./front-end:/app
      - /app/node_modules
    command: npm run docker-dev

  api:
    build: ./back-end
    ports:
      - "4080:3000"  # Next.js default port for API app
    depends_on:
      - sqlite
    environment:
      - NODE_ENV=development
    volumes:
      - ./back-end:/app
      - sqlite_data:/app/sqlite
    command: sh -c "npm run docker-dev"

  sqlite:
    image: alpine
    container_name: sqlite-volume-holder
    volumes:
      - sqlite_data:/sqlite
    command: ["sh", "-c", "while true; do sleep 1000; done"]

volumes:
  sqlite_data:
