import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/global/footer/footer";
import { Header } from "@/components/global/header/header";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("currentTheme")?.value ?? "dark";
  console.log(theme)
  return (
    <html lang="en" data-theme={theme} className={theme}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header theme={theme as "dark" | "light"} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
