FROM node:lts-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx next build

FROM base AS production

RUN apk add --no-cache tini

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/package*.json ./

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/.next ./.next

COPY --from=builder /app/public ./public

ENTRYPOINT ["/sbin/tini", "--"]

EXPOSE 3000

CMD ["npm", "start"]
